// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo9sB5vS9Sjv7A7uWIjfPqTZ6lGHig_VI',
    appId: '1:1055511547119:web:f0a6b2b68e47cba1849f1a',
    messagingSenderId: '1055511547119',
    projectId: 'eshop-979cb',
    authDomain: 'eshop-979cb.firebaseapp.com',
    storageBucket: 'eshop-979cb.appspot.com',
    measurementId: 'G-1M6Y657QZ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUskuakJOd6bvSgD9wbWdL3GWKPWE8bo4',
    appId: '1:1055511547119:android:947e8e3616bacc60849f1a',
    messagingSenderId: '1055511547119',
    projectId: 'eshop-979cb',
    storageBucket: 'eshop-979cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6BGSRx1O1jRxMIjiJpbyw1XHoXnR9-yU',
    appId: '1:1055511547119:ios:2c54c0c1e1c51ee3849f1a',
    messagingSenderId: '1055511547119',
    projectId: 'eshop-979cb',
    storageBucket: 'eshop-979cb.appspot.com',
    androidClientId: '1055511547119-453u6i9evglcrhmhvlod9d0aiqt6cti4.apps.googleusercontent.com',
    iosClientId: '1055511547119-0dvemttfjhprrhuctb5nfnjpi7mtfima.apps.googleusercontent.com',
    iosBundleId: 'com.example.eShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6BGSRx1O1jRxMIjiJpbyw1XHoXnR9-yU',
    appId: '1:1055511547119:ios:5bc5ee81abab7c83849f1a',
    messagingSenderId: '1055511547119',
    projectId: 'eshop-979cb',
    storageBucket: 'eshop-979cb.appspot.com',
    androidClientId: '1055511547119-453u6i9evglcrhmhvlod9d0aiqt6cti4.apps.googleusercontent.com',
    iosClientId: '1055511547119-b44jtvk5fdgimcc7n6tf476te00nroa6.apps.googleusercontent.com',
    iosBundleId: 'com.example.eShop.RunnerTests',
  );
}
